name: Tests with MPT
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: .
      run: npm ci
    - name: Set commit message
      run: |
        COMMIT_MESSAGE=$(echo "${{ github.event.commits[0].message }}" | sed -e 's/[^a-zA-Z0-9]/-/g')
        echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
      shell: bash
    - name: Run Playwright tests
      working-directory: .
      env:
        PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN}}
        PLAYWRIGHT_SERVICE_URL: wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession
        PLAYWRIGHT_SERVICE_RUN_ID: ${{ env.COMMIT_MESSAGE }}-${{ github.run_attempt }}
      run: npx playwright test -c playwright.service.config.ts --workers=20
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10